// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: dart/gateway/resource/v1/resource.proto

package resource

import (
	v1 "github.com/10Narratives/dart/pkg/dart/domain/capabilities/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Resource represents a computation node in the system with specific
// capabilities.
type Resource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name.
	// Format: `projects/{project}/resources/{resource}`
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Compute capabilities of the resource (CPU, GPU).
	ComputeCapabilities *v1.ComputeCapabilities `protobuf:"bytes,2,opt,name=compute_capabilities,json=computeCapabilities,proto3" json:"compute_capabilities,omitempty"`
	// Memory capabilities of the resource.
	MemoryCapabilities *v1.MemoryCapabilities `protobuf:"bytes,3,opt,name=memory_capabilities,json=memoryCapabilities,proto3" json:"memory_capabilities,omitempty"`
	// Network capabilities of the resource.
	NetworkCapabilities *v1.NetworkCapabilities `protobuf:"bytes,4,opt,name=network_capabilities,json=networkCapabilities,proto3" json:"network_capabilities,omitempty"`
	// Task execution capabilities of the resource.
	TaskExecutionCapabilities *v1.TaskExecutionCapabilities `protobuf:"bytes,5,opt,name=task_execution_capabilities,json=taskExecutionCapabilities,proto3" json:"task_execution_capabilities,omitempty"`
	// Output only. Creation timestamp.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// Network address for accessing the resource (e.g.,
	// "worker-123.example.com:8080").
	Address       string `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_dart_gateway_resource_v1_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_dart_gateway_resource_v1_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_dart_gateway_resource_v1_resource_proto_rawDescGZIP(), []int{0}
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resource) GetComputeCapabilities() *v1.ComputeCapabilities {
	if x != nil {
		return x.ComputeCapabilities
	}
	return nil
}

func (x *Resource) GetMemoryCapabilities() *v1.MemoryCapabilities {
	if x != nil {
		return x.MemoryCapabilities
	}
	return nil
}

func (x *Resource) GetNetworkCapabilities() *v1.NetworkCapabilities {
	if x != nil {
		return x.NetworkCapabilities
	}
	return nil
}

func (x *Resource) GetTaskExecutionCapabilities() *v1.TaskExecutionCapabilities {
	if x != nil {
		return x.TaskExecutionCapabilities
	}
	return nil
}

func (x *Resource) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Resource) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_dart_gateway_resource_v1_resource_proto protoreflect.FileDescriptor

const file_dart_gateway_resource_v1_resource_proto_rawDesc = "" +
	"\n" +
	"'dart/gateway/resource/v1/resource.proto\x12\x18dart.gateway.resource.v1\x1a\x19google/api/resource.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\x1a6dart/domain/capabilities/v1/compute_capabilities.proto\x1a5dart/domain/capabilities/v1/memory_capabilities.proto\x1a6dart/domain/capabilities/v1/network_capabilities.proto\x1a=dart/domain/capabilities/v1/task_execution_capabilities.proto\"\x9c\x05\n" +
	"\bResource\x121\n" +
	"\x04name\x18\x01 \x01(\tB\x1d\xe0A\b\xfaA\x17\n" +
	"\x15dart.gateway/ResourceR\x04name\x12c\n" +
	"\x14compute_capabilities\x18\x02 \x01(\v20.dart.domain.capabilities.v1.ComputeCapabilitiesR\x13computeCapabilities\x12`\n" +
	"\x13memory_capabilities\x18\x03 \x01(\v2/.dart.domain.capabilities.v1.MemoryCapabilitiesR\x12memoryCapabilities\x12c\n" +
	"\x14network_capabilities\x18\x04 \x01(\v20.dart.domain.capabilities.v1.NetworkCapabilitiesR\x13networkCapabilities\x12v\n" +
	"\x1btask_execution_capabilities\x18\x05 \x01(\v26.dart.domain.capabilities.v1.TaskExecutionCapabilitiesR\x19taskExecutionCapabilities\x12@\n" +
	"\vcreate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\x12\x1d\n" +
	"\aaddress\x18\a \x01(\tB\x03\xe0A\x02R\aaddress:X\xeaAU\n" +
	"\x15dart.gateway/Resource\x12'projects/{project}/resources/{resource}*\tresources2\bresourceBDZBgithub.com/10Narratives/dart/pkg/dart/gateway/resource/v1;resourceb\x06proto3"

var (
	file_dart_gateway_resource_v1_resource_proto_rawDescOnce sync.Once
	file_dart_gateway_resource_v1_resource_proto_rawDescData []byte
)

func file_dart_gateway_resource_v1_resource_proto_rawDescGZIP() []byte {
	file_dart_gateway_resource_v1_resource_proto_rawDescOnce.Do(func() {
		file_dart_gateway_resource_v1_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dart_gateway_resource_v1_resource_proto_rawDesc), len(file_dart_gateway_resource_v1_resource_proto_rawDesc)))
	})
	return file_dart_gateway_resource_v1_resource_proto_rawDescData
}

var file_dart_gateway_resource_v1_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dart_gateway_resource_v1_resource_proto_goTypes = []any{
	(*Resource)(nil),                     // 0: dart.gateway.resource.v1.Resource
	(*v1.ComputeCapabilities)(nil),       // 1: dart.domain.capabilities.v1.ComputeCapabilities
	(*v1.MemoryCapabilities)(nil),        // 2: dart.domain.capabilities.v1.MemoryCapabilities
	(*v1.NetworkCapabilities)(nil),       // 3: dart.domain.capabilities.v1.NetworkCapabilities
	(*v1.TaskExecutionCapabilities)(nil), // 4: dart.domain.capabilities.v1.TaskExecutionCapabilities
	(*timestamppb.Timestamp)(nil),        // 5: google.protobuf.Timestamp
}
var file_dart_gateway_resource_v1_resource_proto_depIdxs = []int32{
	1, // 0: dart.gateway.resource.v1.Resource.compute_capabilities:type_name -> dart.domain.capabilities.v1.ComputeCapabilities
	2, // 1: dart.gateway.resource.v1.Resource.memory_capabilities:type_name -> dart.domain.capabilities.v1.MemoryCapabilities
	3, // 2: dart.gateway.resource.v1.Resource.network_capabilities:type_name -> dart.domain.capabilities.v1.NetworkCapabilities
	4, // 3: dart.gateway.resource.v1.Resource.task_execution_capabilities:type_name -> dart.domain.capabilities.v1.TaskExecutionCapabilities
	5, // 4: dart.gateway.resource.v1.Resource.create_time:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_dart_gateway_resource_v1_resource_proto_init() }
func file_dart_gateway_resource_v1_resource_proto_init() {
	if File_dart_gateway_resource_v1_resource_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dart_gateway_resource_v1_resource_proto_rawDesc), len(file_dart_gateway_resource_v1_resource_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dart_gateway_resource_v1_resource_proto_goTypes,
		DependencyIndexes: file_dart_gateway_resource_v1_resource_proto_depIdxs,
		MessageInfos:      file_dart_gateway_resource_v1_resource_proto_msgTypes,
	}.Build()
	File_dart_gateway_resource_v1_resource_proto = out.File
	file_dart_gateway_resource_v1_resource_proto_goTypes = nil
	file_dart_gateway_resource_v1_resource_proto_depIdxs = nil
}
