// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: dart/gateway/resource/v1/resource_service.proto

package resource

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListResourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourcesRequest) Reset() {
	*x = ListResourcesRequest{}
	mi := &file_dart_gateway_resource_v1_resource_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesRequest) ProtoMessage() {}

func (x *ListResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dart_gateway_resource_v1_resource_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesRequest.ProtoReflect.Descriptor instead.
func (*ListResourcesRequest) Descriptor() ([]byte, []int) {
	return file_dart_gateway_resource_v1_resource_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListResourcesRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListResourcesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListResourcesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListResourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     []*Resource            `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourcesResponse) Reset() {
	*x = ListResourcesResponse{}
	mi := &file_dart_gateway_resource_v1_resource_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesResponse) ProtoMessage() {}

func (x *ListResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dart_gateway_resource_v1_resource_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesResponse.ProtoReflect.Descriptor instead.
func (*ListResourcesResponse) Descriptor() ([]byte, []int) {
	return file_dart_gateway_resource_v1_resource_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListResourcesResponse) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ListResourcesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceRequest) Reset() {
	*x = GetResourceRequest{}
	mi := &file_dart_gateway_resource_v1_resource_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceRequest) ProtoMessage() {}

func (x *GetResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dart_gateway_resource_v1_resource_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceRequest.ProtoReflect.Descriptor instead.
func (*GetResourceRequest) Descriptor() ([]byte, []int) {
	return file_dart_gateway_resource_v1_resource_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetResourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RegisterResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	ResourceId    string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Resource      *Resource              `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResourceRequest) Reset() {
	*x = RegisterResourceRequest{}
	mi := &file_dart_gateway_resource_v1_resource_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResourceRequest) ProtoMessage() {}

func (x *RegisterResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dart_gateway_resource_v1_resource_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResourceRequest.ProtoReflect.Descriptor instead.
func (*RegisterResourceRequest) Descriptor() ([]byte, []int) {
	return file_dart_gateway_resource_v1_resource_service_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResourceRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *RegisterResourceRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *RegisterResourceRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type UnregisterResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterResourceRequest) Reset() {
	*x = UnregisterResourceRequest{}
	mi := &file_dart_gateway_resource_v1_resource_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterResourceRequest) ProtoMessage() {}

func (x *UnregisterResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dart_gateway_resource_v1_resource_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterResourceRequest.ProtoReflect.Descriptor instead.
func (*UnregisterResourceRequest) Descriptor() ([]byte, []int) {
	return file_dart_gateway_resource_v1_resource_service_proto_rawDescGZIP(), []int{4}
}

func (x *UnregisterResourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_dart_gateway_resource_v1_resource_service_proto protoreflect.FileDescriptor

const file_dart_gateway_resource_v1_resource_service_proto_rawDesc = "" +
	"\n" +
	"/dart/gateway/resource/v1/resource_service.proto\x12\x18dart.gateway.resource.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x19google/api/resource.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a'dart/gateway/resource/v1/resource.proto\"\x92\x01\n" +
	"\x14ListResourcesRequest\x124\n" +
	"\x06parent\x18\x01 \x01(\tB\x1c\xe0A\x02\xfaA\x16\n" +
	"\x14dart.gateway/ProjectR\x06parent\x12 \n" +
	"\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01R\bpageSize\x12\"\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tB\x03\xe0A\x01R\tpageToken\"\x81\x01\n" +
	"\x15ListResourcesResponse\x12@\n" +
	"\tresources\x18\x01 \x03(\v2\".dart.gateway.resource.v1.ResourceR\tresources\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"G\n" +
	"\x12GetResourceRequest\x121\n" +
	"\x04name\x18\x01 \x01(\tB\x1d\xe0A\x02\xfaA\x17\n" +
	"\x15dart.gateway/ResourceR\x04name\"\xba\x01\n" +
	"\x17RegisterResourceRequest\x124\n" +
	"\x06parent\x18\x01 \x01(\tB\x1c\xe0A\x02\xfaA\x16\n" +
	"\x14dart.gateway/ProjectR\x06parent\x12$\n" +
	"\vresource_id\x18\x02 \x01(\tB\x03\xe0A\x01R\n" +
	"resourceId\x12C\n" +
	"\bresource\x18\x03 \x01(\v2\".dart.gateway.resource.v1.ResourceB\x03\xe0A\x02R\bresource\"N\n" +
	"\x19UnregisterResourceRequest\x121\n" +
	"\x04name\x18\x01 \x01(\tB\x1d\xe0A\x02\xfaA\x17\n" +
	"\x15dart.gateway/ResourceR\x04name2\x9b\x05\n" +
	"\x0fResourceService\x12\xa1\x01\n" +
	"\rListResources\x12..dart.gateway.resource.v1.ListResourcesRequest\x1a/.dart.gateway.resource.v1.ListResourcesResponse\"/\x82\xd3\xe4\x93\x02)\x12'/v1alpha1/{parent=projects/*}/resources\x12\x90\x01\n" +
	"\vGetResource\x12,.dart.gateway.resource.v1.GetResourceRequest\x1a\".dart.gateway.resource.v1.Resource\"/\x82\xd3\xe4\x93\x02)\x12'/v1alpha1/{name=projects/*/resources/*}\x12\xad\x01\n" +
	"\x10RegisterResource\x121.dart.gateway.resource.v1.RegisterResourceRequest\x1a\".dart.gateway.resource.v1.Resource\"B\x82\xd3\xe4\x93\x02<:\bresource\"0/v1alpha1/{parent=projects/*}/resources:register\x12\xa0\x01\n" +
	"\x12UnregisterResource\x123.dart.gateway.resource.v1.UnregisterResourceRequest\x1a\x16.google.protobuf.Empty\"=\x82\xd3\xe4\x93\x027:\x01*\"2/v1alpha1/{name=projects/*/resources/*}:unregisterBDZBgithub.com/10Narratives/dart/pkg/dart/gateway/resource/v1;resourceb\x06proto3"

var (
	file_dart_gateway_resource_v1_resource_service_proto_rawDescOnce sync.Once
	file_dart_gateway_resource_v1_resource_service_proto_rawDescData []byte
)

func file_dart_gateway_resource_v1_resource_service_proto_rawDescGZIP() []byte {
	file_dart_gateway_resource_v1_resource_service_proto_rawDescOnce.Do(func() {
		file_dart_gateway_resource_v1_resource_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dart_gateway_resource_v1_resource_service_proto_rawDesc), len(file_dart_gateway_resource_v1_resource_service_proto_rawDesc)))
	})
	return file_dart_gateway_resource_v1_resource_service_proto_rawDescData
}

var file_dart_gateway_resource_v1_resource_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_dart_gateway_resource_v1_resource_service_proto_goTypes = []any{
	(*ListResourcesRequest)(nil),      // 0: dart.gateway.resource.v1.ListResourcesRequest
	(*ListResourcesResponse)(nil),     // 1: dart.gateway.resource.v1.ListResourcesResponse
	(*GetResourceRequest)(nil),        // 2: dart.gateway.resource.v1.GetResourceRequest
	(*RegisterResourceRequest)(nil),   // 3: dart.gateway.resource.v1.RegisterResourceRequest
	(*UnregisterResourceRequest)(nil), // 4: dart.gateway.resource.v1.UnregisterResourceRequest
	(*Resource)(nil),                  // 5: dart.gateway.resource.v1.Resource
	(*emptypb.Empty)(nil),             // 6: google.protobuf.Empty
}
var file_dart_gateway_resource_v1_resource_service_proto_depIdxs = []int32{
	5, // 0: dart.gateway.resource.v1.ListResourcesResponse.resources:type_name -> dart.gateway.resource.v1.Resource
	5, // 1: dart.gateway.resource.v1.RegisterResourceRequest.resource:type_name -> dart.gateway.resource.v1.Resource
	0, // 2: dart.gateway.resource.v1.ResourceService.ListResources:input_type -> dart.gateway.resource.v1.ListResourcesRequest
	2, // 3: dart.gateway.resource.v1.ResourceService.GetResource:input_type -> dart.gateway.resource.v1.GetResourceRequest
	3, // 4: dart.gateway.resource.v1.ResourceService.RegisterResource:input_type -> dart.gateway.resource.v1.RegisterResourceRequest
	4, // 5: dart.gateway.resource.v1.ResourceService.UnregisterResource:input_type -> dart.gateway.resource.v1.UnregisterResourceRequest
	1, // 6: dart.gateway.resource.v1.ResourceService.ListResources:output_type -> dart.gateway.resource.v1.ListResourcesResponse
	5, // 7: dart.gateway.resource.v1.ResourceService.GetResource:output_type -> dart.gateway.resource.v1.Resource
	5, // 8: dart.gateway.resource.v1.ResourceService.RegisterResource:output_type -> dart.gateway.resource.v1.Resource
	6, // 9: dart.gateway.resource.v1.ResourceService.UnregisterResource:output_type -> google.protobuf.Empty
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dart_gateway_resource_v1_resource_service_proto_init() }
func file_dart_gateway_resource_v1_resource_service_proto_init() {
	if File_dart_gateway_resource_v1_resource_service_proto != nil {
		return
	}
	file_dart_gateway_resource_v1_resource_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dart_gateway_resource_v1_resource_service_proto_rawDesc), len(file_dart_gateway_resource_v1_resource_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dart_gateway_resource_v1_resource_service_proto_goTypes,
		DependencyIndexes: file_dart_gateway_resource_v1_resource_service_proto_depIdxs,
		MessageInfos:      file_dart_gateway_resource_v1_resource_service_proto_msgTypes,
	}.Build()
	File_dart_gateway_resource_v1_resource_service_proto = out.File
	file_dart_gateway_resource_v1_resource_service_proto_goTypes = nil
	file_dart_gateway_resource_v1_resource_service_proto_depIdxs = nil
}
