// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: dart/domain/capabilities/v1/compute_capabilities.proto

package capabilities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ComputeCapabilities struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of CPU cores available
	CpuCores int32 `protobuf:"varint,1,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	// Number of GPU devices available
	GpuCount int32 `protobuf:"varint,2,opt,name=gpu_count,json=gpuCount,proto3" json:"gpu_count,omitempty"`
	// Type of GPU available (e.g., "NVIDIA_A100", "AMD_MI210")
	GpuType       string `protobuf:"bytes,3,opt,name=gpu_type,json=gpuType,proto3" json:"gpu_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeCapabilities) Reset() {
	*x = ComputeCapabilities{}
	mi := &file_dart_domain_capabilities_v1_compute_capabilities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeCapabilities) ProtoMessage() {}

func (x *ComputeCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_dart_domain_capabilities_v1_compute_capabilities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeCapabilities.ProtoReflect.Descriptor instead.
func (*ComputeCapabilities) Descriptor() ([]byte, []int) {
	return file_dart_domain_capabilities_v1_compute_capabilities_proto_rawDescGZIP(), []int{0}
}

func (x *ComputeCapabilities) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *ComputeCapabilities) GetGpuCount() int32 {
	if x != nil {
		return x.GpuCount
	}
	return 0
}

func (x *ComputeCapabilities) GetGpuType() string {
	if x != nil {
		return x.GpuType
	}
	return ""
}

var File_dart_domain_capabilities_v1_compute_capabilities_proto protoreflect.FileDescriptor

const file_dart_domain_capabilities_v1_compute_capabilities_proto_rawDesc = "" +
	"\n" +
	"6dart/domain/capabilities/v1/compute_capabilities.proto\x12\x1bdart.domain.capabilities.v1\"j\n" +
	"\x13ComputeCapabilities\x12\x1b\n" +
	"\tcpu_cores\x18\x01 \x01(\x05R\bcpuCores\x12\x1b\n" +
	"\tgpu_count\x18\x02 \x01(\x05R\bgpuCount\x12\x19\n" +
	"\bgpu_type\x18\x03 \x01(\tR\agpuTypeBKZIgithub.com/10Narratives/dart/pkg/dart/domain/capabilities/v1;capabilitiesb\x06proto3"

var (
	file_dart_domain_capabilities_v1_compute_capabilities_proto_rawDescOnce sync.Once
	file_dart_domain_capabilities_v1_compute_capabilities_proto_rawDescData []byte
)

func file_dart_domain_capabilities_v1_compute_capabilities_proto_rawDescGZIP() []byte {
	file_dart_domain_capabilities_v1_compute_capabilities_proto_rawDescOnce.Do(func() {
		file_dart_domain_capabilities_v1_compute_capabilities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dart_domain_capabilities_v1_compute_capabilities_proto_rawDesc), len(file_dart_domain_capabilities_v1_compute_capabilities_proto_rawDesc)))
	})
	return file_dart_domain_capabilities_v1_compute_capabilities_proto_rawDescData
}

var file_dart_domain_capabilities_v1_compute_capabilities_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dart_domain_capabilities_v1_compute_capabilities_proto_goTypes = []any{
	(*ComputeCapabilities)(nil), // 0: dart.domain.capabilities.v1.ComputeCapabilities
}
var file_dart_domain_capabilities_v1_compute_capabilities_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dart_domain_capabilities_v1_compute_capabilities_proto_init() }
func file_dart_domain_capabilities_v1_compute_capabilities_proto_init() {
	if File_dart_domain_capabilities_v1_compute_capabilities_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dart_domain_capabilities_v1_compute_capabilities_proto_rawDesc), len(file_dart_domain_capabilities_v1_compute_capabilities_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dart_domain_capabilities_v1_compute_capabilities_proto_goTypes,
		DependencyIndexes: file_dart_domain_capabilities_v1_compute_capabilities_proto_depIdxs,
		MessageInfos:      file_dart_domain_capabilities_v1_compute_capabilities_proto_msgTypes,
	}.Build()
	File_dart_domain_capabilities_v1_compute_capabilities_proto = out.File
	file_dart_domain_capabilities_v1_compute_capabilities_proto_goTypes = nil
	file_dart_domain_capabilities_v1_compute_capabilities_proto_depIdxs = nil
}
