// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: dart/domain/capabilities/v1/memory_capabilities.proto

package capabilities

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on MemoryCapabilities with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *MemoryCapabilities) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MemoryCapabilities with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MemoryCapabilitiesMultiError, or nil if none found.
func (m *MemoryCapabilities) ValidateAll() error {
	return m.validate(true)
}

func (m *MemoryCapabilities) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for MemoryBytes

	// no validation rules for StorageBytes

	if len(errors) > 0 {
		return MemoryCapabilitiesMultiError(errors)
	}

	return nil
}

// MemoryCapabilitiesMultiError is an error wrapping multiple validation errors
// returned by MemoryCapabilities.ValidateAll() if the designated constraints
// aren't met.
type MemoryCapabilitiesMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MemoryCapabilitiesMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MemoryCapabilitiesMultiError) AllErrors() []error { return m }

// MemoryCapabilitiesValidationError is the validation error returned by
// MemoryCapabilities.Validate if the designated constraints aren't met.
type MemoryCapabilitiesValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MemoryCapabilitiesValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MemoryCapabilitiesValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MemoryCapabilitiesValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MemoryCapabilitiesValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MemoryCapabilitiesValidationError) ErrorName() string {
	return "MemoryCapabilitiesValidationError"
}

// Error satisfies the builtin error interface
func (e MemoryCapabilitiesValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMemoryCapabilities.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MemoryCapabilitiesValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MemoryCapabilitiesValidationError{}
