// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: dart/domain/capabilities/v1/memory_capabilities.proto

package capabilities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MemoryCapabilities struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Amount of memory in bytes
	MemoryBytes int64 `protobuf:"varint,1,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	// Storage capacity in bytes
	StorageBytes  int64 `protobuf:"varint,2,opt,name=storage_bytes,json=storageBytes,proto3" json:"storage_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryCapabilities) Reset() {
	*x = MemoryCapabilities{}
	mi := &file_dart_domain_capabilities_v1_memory_capabilities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryCapabilities) ProtoMessage() {}

func (x *MemoryCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_dart_domain_capabilities_v1_memory_capabilities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryCapabilities.ProtoReflect.Descriptor instead.
func (*MemoryCapabilities) Descriptor() ([]byte, []int) {
	return file_dart_domain_capabilities_v1_memory_capabilities_proto_rawDescGZIP(), []int{0}
}

func (x *MemoryCapabilities) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *MemoryCapabilities) GetStorageBytes() int64 {
	if x != nil {
		return x.StorageBytes
	}
	return 0
}

var File_dart_domain_capabilities_v1_memory_capabilities_proto protoreflect.FileDescriptor

const file_dart_domain_capabilities_v1_memory_capabilities_proto_rawDesc = "" +
	"\n" +
	"5dart/domain/capabilities/v1/memory_capabilities.proto\x12\x1bdart.domain.capabilities.v1\"\\\n" +
	"\x12MemoryCapabilities\x12!\n" +
	"\fmemory_bytes\x18\x01 \x01(\x03R\vmemoryBytes\x12#\n" +
	"\rstorage_bytes\x18\x02 \x01(\x03R\fstorageBytesBKZIgithub.com/10Narratives/dart/pkg/dart/domain/capabilities/v1;capabilitiesb\x06proto3"

var (
	file_dart_domain_capabilities_v1_memory_capabilities_proto_rawDescOnce sync.Once
	file_dart_domain_capabilities_v1_memory_capabilities_proto_rawDescData []byte
)

func file_dart_domain_capabilities_v1_memory_capabilities_proto_rawDescGZIP() []byte {
	file_dart_domain_capabilities_v1_memory_capabilities_proto_rawDescOnce.Do(func() {
		file_dart_domain_capabilities_v1_memory_capabilities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dart_domain_capabilities_v1_memory_capabilities_proto_rawDesc), len(file_dart_domain_capabilities_v1_memory_capabilities_proto_rawDesc)))
	})
	return file_dart_domain_capabilities_v1_memory_capabilities_proto_rawDescData
}

var file_dart_domain_capabilities_v1_memory_capabilities_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dart_domain_capabilities_v1_memory_capabilities_proto_goTypes = []any{
	(*MemoryCapabilities)(nil), // 0: dart.domain.capabilities.v1.MemoryCapabilities
}
var file_dart_domain_capabilities_v1_memory_capabilities_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dart_domain_capabilities_v1_memory_capabilities_proto_init() }
func file_dart_domain_capabilities_v1_memory_capabilities_proto_init() {
	if File_dart_domain_capabilities_v1_memory_capabilities_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dart_domain_capabilities_v1_memory_capabilities_proto_rawDesc), len(file_dart_domain_capabilities_v1_memory_capabilities_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dart_domain_capabilities_v1_memory_capabilities_proto_goTypes,
		DependencyIndexes: file_dart_domain_capabilities_v1_memory_capabilities_proto_depIdxs,
		MessageInfos:      file_dart_domain_capabilities_v1_memory_capabilities_proto_msgTypes,
	}.Build()
	File_dart_domain_capabilities_v1_memory_capabilities_proto = out.File
	file_dart_domain_capabilities_v1_memory_capabilities_proto_goTypes = nil
	file_dart_domain_capabilities_v1_memory_capabilities_proto_depIdxs = nil
}
