// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: dart/domain/capabilities/v1/network_capabilities.proto

package capabilities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NetworkCapabilities struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Network bandwidth in bits per second
	NetworkBandwidthBps int64 `protobuf:"varint,1,opt,name=network_bandwidth_bps,json=networkBandwidthBps,proto3" json:"network_bandwidth_bps,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *NetworkCapabilities) Reset() {
	*x = NetworkCapabilities{}
	mi := &file_dart_domain_capabilities_v1_network_capabilities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkCapabilities) ProtoMessage() {}

func (x *NetworkCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_dart_domain_capabilities_v1_network_capabilities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkCapabilities.ProtoReflect.Descriptor instead.
func (*NetworkCapabilities) Descriptor() ([]byte, []int) {
	return file_dart_domain_capabilities_v1_network_capabilities_proto_rawDescGZIP(), []int{0}
}

func (x *NetworkCapabilities) GetNetworkBandwidthBps() int64 {
	if x != nil {
		return x.NetworkBandwidthBps
	}
	return 0
}

var File_dart_domain_capabilities_v1_network_capabilities_proto protoreflect.FileDescriptor

const file_dart_domain_capabilities_v1_network_capabilities_proto_rawDesc = "" +
	"\n" +
	"6dart/domain/capabilities/v1/network_capabilities.proto\x12\x1bdart.domain.capabilities.v1\"I\n" +
	"\x13NetworkCapabilities\x122\n" +
	"\x15network_bandwidth_bps\x18\x01 \x01(\x03R\x13networkBandwidthBpsBKZIgithub.com/10Narratives/dart/pkg/dart/domain/capabilities/v1;capabilitiesb\x06proto3"

var (
	file_dart_domain_capabilities_v1_network_capabilities_proto_rawDescOnce sync.Once
	file_dart_domain_capabilities_v1_network_capabilities_proto_rawDescData []byte
)

func file_dart_domain_capabilities_v1_network_capabilities_proto_rawDescGZIP() []byte {
	file_dart_domain_capabilities_v1_network_capabilities_proto_rawDescOnce.Do(func() {
		file_dart_domain_capabilities_v1_network_capabilities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dart_domain_capabilities_v1_network_capabilities_proto_rawDesc), len(file_dart_domain_capabilities_v1_network_capabilities_proto_rawDesc)))
	})
	return file_dart_domain_capabilities_v1_network_capabilities_proto_rawDescData
}

var file_dart_domain_capabilities_v1_network_capabilities_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dart_domain_capabilities_v1_network_capabilities_proto_goTypes = []any{
	(*NetworkCapabilities)(nil), // 0: dart.domain.capabilities.v1.NetworkCapabilities
}
var file_dart_domain_capabilities_v1_network_capabilities_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dart_domain_capabilities_v1_network_capabilities_proto_init() }
func file_dart_domain_capabilities_v1_network_capabilities_proto_init() {
	if File_dart_domain_capabilities_v1_network_capabilities_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dart_domain_capabilities_v1_network_capabilities_proto_rawDesc), len(file_dart_domain_capabilities_v1_network_capabilities_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dart_domain_capabilities_v1_network_capabilities_proto_goTypes,
		DependencyIndexes: file_dart_domain_capabilities_v1_network_capabilities_proto_depIdxs,
		MessageInfos:      file_dart_domain_capabilities_v1_network_capabilities_proto_msgTypes,
	}.Build()
	File_dart_domain_capabilities_v1_network_capabilities_proto = out.File
	file_dart_domain_capabilities_v1_network_capabilities_proto_goTypes = nil
	file_dart_domain_capabilities_v1_network_capabilities_proto_depIdxs = nil
}
