// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: dart/domain/capabilities/v1/task_execution_capabilities.proto

package capabilities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskExecutionCapabilities struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of agent types this resource can execute
	SupportedAgents []string `protobuf:"bytes,1,rep,name=supported_agents,json=supportedAgents,proto3" json:"supported_agents,omitempty"`
	// Maximum number of concurrent tasks this resource can handle
	MaxConcurrentTasks int32 `protobuf:"varint,2,opt,name=max_concurrent_tasks,json=maxConcurrentTasks,proto3" json:"max_concurrent_tasks,omitempty"`
	// Minimum task duration in seconds this resource is optimized for
	MinTaskDurationS float32 `protobuf:"fixed32,3,opt,name=min_task_duration_s,json=minTaskDurationS,proto3" json:"min_task_duration_s,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TaskExecutionCapabilities) Reset() {
	*x = TaskExecutionCapabilities{}
	mi := &file_dart_domain_capabilities_v1_task_execution_capabilities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskExecutionCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExecutionCapabilities) ProtoMessage() {}

func (x *TaskExecutionCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_dart_domain_capabilities_v1_task_execution_capabilities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskExecutionCapabilities.ProtoReflect.Descriptor instead.
func (*TaskExecutionCapabilities) Descriptor() ([]byte, []int) {
	return file_dart_domain_capabilities_v1_task_execution_capabilities_proto_rawDescGZIP(), []int{0}
}

func (x *TaskExecutionCapabilities) GetSupportedAgents() []string {
	if x != nil {
		return x.SupportedAgents
	}
	return nil
}

func (x *TaskExecutionCapabilities) GetMaxConcurrentTasks() int32 {
	if x != nil {
		return x.MaxConcurrentTasks
	}
	return 0
}

func (x *TaskExecutionCapabilities) GetMinTaskDurationS() float32 {
	if x != nil {
		return x.MinTaskDurationS
	}
	return 0
}

var File_dart_domain_capabilities_v1_task_execution_capabilities_proto protoreflect.FileDescriptor

const file_dart_domain_capabilities_v1_task_execution_capabilities_proto_rawDesc = "" +
	"\n" +
	"=dart/domain/capabilities/v1/task_execution_capabilities.proto\x12\x1bdart.domain.capabilities.v1\"\xa7\x01\n" +
	"\x19TaskExecutionCapabilities\x12)\n" +
	"\x10supported_agents\x18\x01 \x03(\tR\x0fsupportedAgents\x120\n" +
	"\x14max_concurrent_tasks\x18\x02 \x01(\x05R\x12maxConcurrentTasks\x12-\n" +
	"\x13min_task_duration_s\x18\x03 \x01(\x02R\x10minTaskDurationSBKZIgithub.com/10Narratives/dart/pkg/dart/domain/capabilities/v1;capabilitiesb\x06proto3"

var (
	file_dart_domain_capabilities_v1_task_execution_capabilities_proto_rawDescOnce sync.Once
	file_dart_domain_capabilities_v1_task_execution_capabilities_proto_rawDescData []byte
)

func file_dart_domain_capabilities_v1_task_execution_capabilities_proto_rawDescGZIP() []byte {
	file_dart_domain_capabilities_v1_task_execution_capabilities_proto_rawDescOnce.Do(func() {
		file_dart_domain_capabilities_v1_task_execution_capabilities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dart_domain_capabilities_v1_task_execution_capabilities_proto_rawDesc), len(file_dart_domain_capabilities_v1_task_execution_capabilities_proto_rawDesc)))
	})
	return file_dart_domain_capabilities_v1_task_execution_capabilities_proto_rawDescData
}

var file_dart_domain_capabilities_v1_task_execution_capabilities_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dart_domain_capabilities_v1_task_execution_capabilities_proto_goTypes = []any{
	(*TaskExecutionCapabilities)(nil), // 0: dart.domain.capabilities.v1.TaskExecutionCapabilities
}
var file_dart_domain_capabilities_v1_task_execution_capabilities_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dart_domain_capabilities_v1_task_execution_capabilities_proto_init() }
func file_dart_domain_capabilities_v1_task_execution_capabilities_proto_init() {
	if File_dart_domain_capabilities_v1_task_execution_capabilities_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dart_domain_capabilities_v1_task_execution_capabilities_proto_rawDesc), len(file_dart_domain_capabilities_v1_task_execution_capabilities_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dart_domain_capabilities_v1_task_execution_capabilities_proto_goTypes,
		DependencyIndexes: file_dart_domain_capabilities_v1_task_execution_capabilities_proto_depIdxs,
		MessageInfos:      file_dart_domain_capabilities_v1_task_execution_capabilities_proto_msgTypes,
	}.Build()
	File_dart_domain_capabilities_v1_task_execution_capabilities_proto = out.File
	file_dart_domain_capabilities_v1_task_execution_capabilities_proto_goTypes = nil
	file_dart_domain_capabilities_v1_task_execution_capabilities_proto_depIdxs = nil
}
