// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: dart/gateway/project/v1/project.proto

package project

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_dart_gateway_project_v1_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_dart_gateway_project_v1_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_dart_gateway_project_v1_project_proto_rawDescGZIP(), []int{0}
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Project) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Project) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Project) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

var File_dart_gateway_project_v1_project_proto protoreflect.FileDescriptor

const file_dart_gateway_project_v1_project_proto_rawDesc = "" +
	"\n" +
	"%dart/gateway/project/v1/project.proto\x12\x17dart.gateway.project.v1\x1a\x19google/api/resource.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc6\x02\n" +
	"\aProject\x120\n" +
	"\x04name\x18\x01 \x01(\tB\x1c\xe0A\b\xfaA\x16\n" +
	"\x14dart.gateway/ProjectR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12@\n" +
	"\vcreate_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\x12@\n" +
	"\vupdate_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"updateTime:@\xeaA=\n" +
	"\x14dart.gateway/Project\x12\x12projects/{project}*\bprojects2\aprojectBBZ@github.com/10Narratives/dart/pkg/dart/gateway/project/v1;projectb\x06proto3"

var (
	file_dart_gateway_project_v1_project_proto_rawDescOnce sync.Once
	file_dart_gateway_project_v1_project_proto_rawDescData []byte
)

func file_dart_gateway_project_v1_project_proto_rawDescGZIP() []byte {
	file_dart_gateway_project_v1_project_proto_rawDescOnce.Do(func() {
		file_dart_gateway_project_v1_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dart_gateway_project_v1_project_proto_rawDesc), len(file_dart_gateway_project_v1_project_proto_rawDesc)))
	})
	return file_dart_gateway_project_v1_project_proto_rawDescData
}

var file_dart_gateway_project_v1_project_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dart_gateway_project_v1_project_proto_goTypes = []any{
	(*Project)(nil),               // 0: dart.gateway.project.v1.Project
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_dart_gateway_project_v1_project_proto_depIdxs = []int32{
	1, // 0: dart.gateway.project.v1.Project.create_time:type_name -> google.protobuf.Timestamp
	1, // 1: dart.gateway.project.v1.Project.update_time:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dart_gateway_project_v1_project_proto_init() }
func file_dart_gateway_project_v1_project_proto_init() {
	if File_dart_gateway_project_v1_project_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dart_gateway_project_v1_project_proto_rawDesc), len(file_dart_gateway_project_v1_project_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dart_gateway_project_v1_project_proto_goTypes,
		DependencyIndexes: file_dart_gateway_project_v1_project_proto_depIdxs,
		MessageInfos:      file_dart_gateway_project_v1_project_proto_msgTypes,
	}.Build()
	File_dart_gateway_project_v1_project_proto = out.File
	file_dart_gateway_project_v1_project_proto_goTypes = nil
	file_dart_gateway_project_v1_project_proto_depIdxs = nil
}
