// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: dart/gateway/project/v1/project_service.proto

package project

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsRequest) Reset() {
	*x = ListProjectsRequest{}
	mi := &file_dart_gateway_project_v1_project_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsRequest) ProtoMessage() {}

func (x *ListProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dart_gateway_project_v1_project_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return file_dart_gateway_project_v1_project_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListProjectsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListProjectsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*Project             `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_dart_gateway_project_v1_project_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dart_gateway_project_v1_project_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_dart_gateway_project_v1_project_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListProjectsResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *ListProjectsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectRequest) Reset() {
	*x = GetProjectRequest{}
	mi := &file_dart_gateway_project_v1_project_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectRequest) ProtoMessage() {}

func (x *GetProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dart_gateway_project_v1_project_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectRequest.ProtoReflect.Descriptor instead.
func (*GetProjectRequest) Descriptor() ([]byte, []int) {
	return file_dart_gateway_project_v1_project_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Project       *Project               `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectRequest) Reset() {
	*x = CreateProjectRequest{}
	mi := &file_dart_gateway_project_v1_project_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectRequest) ProtoMessage() {}

func (x *CreateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dart_gateway_project_v1_project_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return file_dart_gateway_project_v1_project_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateProjectRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateProjectRequest) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

type UpdateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *Project               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectRequest) Reset() {
	*x = UpdateProjectRequest{}
	mi := &file_dart_gateway_project_v1_project_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectRequest) ProtoMessage() {}

func (x *UpdateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dart_gateway_project_v1_project_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectRequest.ProtoReflect.Descriptor instead.
func (*UpdateProjectRequest) Descriptor() ([]byte, []int) {
	return file_dart_gateway_project_v1_project_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateProjectRequest) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *UpdateProjectRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeleteProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectRequest) Reset() {
	*x = DeleteProjectRequest{}
	mi := &file_dart_gateway_project_v1_project_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectRequest) ProtoMessage() {}

func (x *DeleteProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dart_gateway_project_v1_project_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectRequest.ProtoReflect.Descriptor instead.
func (*DeleteProjectRequest) Descriptor() ([]byte, []int) {
	return file_dart_gateway_project_v1_project_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_dart_gateway_project_v1_project_service_proto protoreflect.FileDescriptor

const file_dart_gateway_project_v1_project_service_proto_rawDesc = "" +
	"\n" +
	"-dart/gateway/project/v1/project_service.proto\x12\x17dart.gateway.project.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x19google/api/resource.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a%dart/gateway/project/v1/project.proto\"Q\n" +
	"\x13ListProjectsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"|\n" +
	"\x14ListProjectsResponse\x12<\n" +
	"\bprojects\x18\x01 \x03(\v2 .dart.gateway.project.v1.ProjectR\bprojects\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"E\n" +
	"\x11GetProjectRequest\x120\n" +
	"\x04name\x18\x01 \x01(\tB\x1c\xe0A\x02\xfaA\x16\n" +
	"\x14dart.gateway/ProjectR\x04name\"{\n" +
	"\x14CreateProjectRequest\x12\"\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x03\xe0A\x01R\tprojectId\x12?\n" +
	"\aproject\x18\x02 \x01(\v2 .dart.gateway.project.v1.ProjectB\x03\xe0A\x02R\aproject\"\x94\x01\n" +
	"\x14UpdateProjectRequest\x12?\n" +
	"\aproject\x18\x01 \x01(\v2 .dart.gateway.project.v1.ProjectB\x03\xe0A\x02R\aproject\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"H\n" +
	"\x14DeleteProjectRequest\x120\n" +
	"\x04name\x18\x01 \x01(\tB\x1c\xe0A\x02\xfaA\x16\n" +
	"\x14dart.gateway/ProjectR\x04name2\xb9\x05\n" +
	"\x0eProjectService\x12\x87\x01\n" +
	"\fListProjects\x12,.dart.gateway.project.v1.ListProjectsRequest\x1a-.dart.gateway.project.v1.ListProjectsResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1alpha1/projects\x12\x7f\n" +
	"\n" +
	"GetProject\x12*.dart.gateway.project.v1.GetProjectRequest\x1a .dart.gateway.project.v1.Project\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1alpha1/{name=projects/*}\x12\x85\x01\n" +
	"\rCreateProject\x12-.dart.gateway.project.v1.CreateProjectRequest\x1a .dart.gateway.project.v1.Project\"#\x82\xd3\xe4\x93\x02\x1d:\aproject\"\x12/v1alpha1/projects\x12\x96\x01\n" +
	"\rUpdateProject\x12-.dart.gateway.project.v1.UpdateProjectRequest\x1a .dart.gateway.project.v1.Project\"4\x82\xd3\xe4\x93\x02.:\aproject2#/v1alpha1/{project.name=projects/*}\x12{\n" +
	"\rDeleteProject\x12-.dart.gateway.project.v1.DeleteProjectRequest\x1a\x16.google.protobuf.Empty\"#\x82\xd3\xe4\x93\x02\x1d*\x1b/v1alpha1/{name=projects/*}BBZ@github.com/10Narratives/dart/pkg/dart/gateway/project/v1;projectb\x06proto3"

var (
	file_dart_gateway_project_v1_project_service_proto_rawDescOnce sync.Once
	file_dart_gateway_project_v1_project_service_proto_rawDescData []byte
)

func file_dart_gateway_project_v1_project_service_proto_rawDescGZIP() []byte {
	file_dart_gateway_project_v1_project_service_proto_rawDescOnce.Do(func() {
		file_dart_gateway_project_v1_project_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dart_gateway_project_v1_project_service_proto_rawDesc), len(file_dart_gateway_project_v1_project_service_proto_rawDesc)))
	})
	return file_dart_gateway_project_v1_project_service_proto_rawDescData
}

var file_dart_gateway_project_v1_project_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_dart_gateway_project_v1_project_service_proto_goTypes = []any{
	(*ListProjectsRequest)(nil),   // 0: dart.gateway.project.v1.ListProjectsRequest
	(*ListProjectsResponse)(nil),  // 1: dart.gateway.project.v1.ListProjectsResponse
	(*GetProjectRequest)(nil),     // 2: dart.gateway.project.v1.GetProjectRequest
	(*CreateProjectRequest)(nil),  // 3: dart.gateway.project.v1.CreateProjectRequest
	(*UpdateProjectRequest)(nil),  // 4: dart.gateway.project.v1.UpdateProjectRequest
	(*DeleteProjectRequest)(nil),  // 5: dart.gateway.project.v1.DeleteProjectRequest
	(*Project)(nil),               // 6: dart.gateway.project.v1.Project
	(*fieldmaskpb.FieldMask)(nil), // 7: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),         // 8: google.protobuf.Empty
}
var file_dart_gateway_project_v1_project_service_proto_depIdxs = []int32{
	6, // 0: dart.gateway.project.v1.ListProjectsResponse.projects:type_name -> dart.gateway.project.v1.Project
	6, // 1: dart.gateway.project.v1.CreateProjectRequest.project:type_name -> dart.gateway.project.v1.Project
	6, // 2: dart.gateway.project.v1.UpdateProjectRequest.project:type_name -> dart.gateway.project.v1.Project
	7, // 3: dart.gateway.project.v1.UpdateProjectRequest.update_mask:type_name -> google.protobuf.FieldMask
	0, // 4: dart.gateway.project.v1.ProjectService.ListProjects:input_type -> dart.gateway.project.v1.ListProjectsRequest
	2, // 5: dart.gateway.project.v1.ProjectService.GetProject:input_type -> dart.gateway.project.v1.GetProjectRequest
	3, // 6: dart.gateway.project.v1.ProjectService.CreateProject:input_type -> dart.gateway.project.v1.CreateProjectRequest
	4, // 7: dart.gateway.project.v1.ProjectService.UpdateProject:input_type -> dart.gateway.project.v1.UpdateProjectRequest
	5, // 8: dart.gateway.project.v1.ProjectService.DeleteProject:input_type -> dart.gateway.project.v1.DeleteProjectRequest
	1, // 9: dart.gateway.project.v1.ProjectService.ListProjects:output_type -> dart.gateway.project.v1.ListProjectsResponse
	6, // 10: dart.gateway.project.v1.ProjectService.GetProject:output_type -> dart.gateway.project.v1.Project
	6, // 11: dart.gateway.project.v1.ProjectService.CreateProject:output_type -> dart.gateway.project.v1.Project
	6, // 12: dart.gateway.project.v1.ProjectService.UpdateProject:output_type -> dart.gateway.project.v1.Project
	8, // 13: dart.gateway.project.v1.ProjectService.DeleteProject:output_type -> google.protobuf.Empty
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_dart_gateway_project_v1_project_service_proto_init() }
func file_dart_gateway_project_v1_project_service_proto_init() {
	if File_dart_gateway_project_v1_project_service_proto != nil {
		return
	}
	file_dart_gateway_project_v1_project_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dart_gateway_project_v1_project_service_proto_rawDesc), len(file_dart_gateway_project_v1_project_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dart_gateway_project_v1_project_service_proto_goTypes,
		DependencyIndexes: file_dart_gateway_project_v1_project_service_proto_depIdxs,
		MessageInfos:      file_dart_gateway_project_v1_project_service_proto_msgTypes,
	}.Build()
	File_dart_gateway_project_v1_project_service_proto = out.File
	file_dart_gateway_project_v1_project_service_proto_goTypes = nil
	file_dart_gateway_project_v1_project_service_proto_depIdxs = nil
}
