// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: dart/gateway/agent/v1/agent_service.proto

package agent

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListAgentsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The project to list agents from.
	// Format: `projects/{project}`
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The maximum number of agents to return.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// A page token, received from a previous `ListAgents` call.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_dart_gateway_agent_v1_agent_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dart_gateway_agent_v1_agent_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_dart_gateway_agent_v1_agent_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListAgentsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListAgentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAgentsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListAgentsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of agents.
	Agents []*Agent `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	// A token to retrieve the next page of results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_dart_gateway_agent_v1_agent_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dart_gateway_agent_v1_agent_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_dart_gateway_agent_v1_agent_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListAgentsResponse) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *ListAgentsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetAgentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The resource name of the agent to retrieve.
	// Format: `projects/{project}/agents/{agent}`
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_dart_gateway_agent_v1_agent_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dart_gateway_agent_v1_agent_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_dart_gateway_agent_v1_agent_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetAgentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateAgentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The project in which to create the agent.
	// Format: `projects/{project}`
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Optional. The agent ID to use for this agent.
	AgentId string `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Required. The agent to create.
	Agent         *Agent `protobuf:"bytes,3,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAgentRequest) Reset() {
	*x = CreateAgentRequest{}
	mi := &file_dart_gateway_agent_v1_agent_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentRequest) ProtoMessage() {}

func (x *CreateAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dart_gateway_agent_v1_agent_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentRequest.ProtoReflect.Descriptor instead.
func (*CreateAgentRequest) Descriptor() ([]byte, []int) {
	return file_dart_gateway_agent_v1_agent_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAgentRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CreateAgentRequest) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

type DeleteAgentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The resource name of the agent to delete.
	// Format: `projects/{project}/agents/{agent}`
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAgentRequest) Reset() {
	*x = DeleteAgentRequest{}
	mi := &file_dart_gateway_agent_v1_agent_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgentRequest) ProtoMessage() {}

func (x *DeleteAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dart_gateway_agent_v1_agent_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgentRequest.ProtoReflect.Descriptor instead.
func (*DeleteAgentRequest) Descriptor() ([]byte, []int) {
	return file_dart_gateway_agent_v1_agent_service_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteAgentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_dart_gateway_agent_v1_agent_service_proto protoreflect.FileDescriptor

const file_dart_gateway_agent_v1_agent_service_proto_rawDesc = "" +
	"\n" +
	")dart/gateway/agent/v1/agent_service.proto\x12\x15dart.gateway.agent.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x19google/api/resource.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a!dart/gateway/agent/v1/agent.proto\"\x8f\x01\n" +
	"\x11ListAgentsRequest\x124\n" +
	"\x06parent\x18\x01 \x01(\tB\x1c\xe0A\x02\xfaA\x16\n" +
	"\x14dart.gateway/ProjectR\x06parent\x12 \n" +
	"\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01R\bpageSize\x12\"\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tB\x03\xe0A\x01R\tpageToken\"r\n" +
	"\x12ListAgentsResponse\x124\n" +
	"\x06agents\x18\x01 \x03(\v2\x1c.dart.gateway.agent.v1.AgentR\x06agents\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"A\n" +
	"\x0fGetAgentRequest\x12.\n" +
	"\x04name\x18\x01 \x01(\tB\x1a\xe0A\x02\xfaA\x14\n" +
	"\x12dart.gateway/AgentR\x04name\"\xa3\x01\n" +
	"\x12CreateAgentRequest\x124\n" +
	"\x06parent\x18\x01 \x01(\tB\x1c\xe0A\x02\xfaA\x16\n" +
	"\x14dart.gateway/ProjectR\x06parent\x12\x1e\n" +
	"\bagent_id\x18\x02 \x01(\tB\x03\xe0A\x01R\aagentId\x127\n" +
	"\x05agent\x18\x03 \x01(\v2\x1c.dart.gateway.agent.v1.AgentB\x03\xe0A\x02R\x05agent\"D\n" +
	"\x12DeleteAgentRequest\x12.\n" +
	"\x04name\x18\x01 \x01(\tB\x1a\xe0A\x02\xfaA\x14\n" +
	"\x12dart.gateway/AgentR\x04name2\xae\x04\n" +
	"\fAgentService\x12\x8f\x01\n" +
	"\n" +
	"ListAgents\x12(.dart.gateway.agent.v1.ListAgentsRequest\x1a).dart.gateway.agent.v1.ListAgentsResponse\",\x82\xd3\xe4\x93\x02&\x12$/v1alpha1/{parent=projects/*}/agents\x12~\n" +
	"\bGetAgent\x12&.dart.gateway.agent.v1.GetAgentRequest\x1a\x1c.dart.gateway.agent.v1.Agent\",\x82\xd3\xe4\x93\x02&\x12$/v1alpha1/{name=projects/*/agents/*}\x12\x8b\x01\n" +
	"\vCreateAgent\x12).dart.gateway.agent.v1.CreateAgentRequest\x1a\x1c.dart.gateway.agent.v1.Agent\"3\x82\xd3\xe4\x93\x02-:\x05agent\"$/v1alpha1/{parent=projects/*}/agents\x12~\n" +
	"\vDeleteAgent\x12).dart.gateway.agent.v1.DeleteAgentRequest\x1a\x16.google.protobuf.Empty\",\x82\xd3\xe4\x93\x02&*$/v1alpha1/{name=projects/*/agents/*}B>Z<github.com/10Narratives/dart/pkg/dart/gateway/agent/v1;agentb\x06proto3"

var (
	file_dart_gateway_agent_v1_agent_service_proto_rawDescOnce sync.Once
	file_dart_gateway_agent_v1_agent_service_proto_rawDescData []byte
)

func file_dart_gateway_agent_v1_agent_service_proto_rawDescGZIP() []byte {
	file_dart_gateway_agent_v1_agent_service_proto_rawDescOnce.Do(func() {
		file_dart_gateway_agent_v1_agent_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dart_gateway_agent_v1_agent_service_proto_rawDesc), len(file_dart_gateway_agent_v1_agent_service_proto_rawDesc)))
	})
	return file_dart_gateway_agent_v1_agent_service_proto_rawDescData
}

var file_dart_gateway_agent_v1_agent_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_dart_gateway_agent_v1_agent_service_proto_goTypes = []any{
	(*ListAgentsRequest)(nil),  // 0: dart.gateway.agent.v1.ListAgentsRequest
	(*ListAgentsResponse)(nil), // 1: dart.gateway.agent.v1.ListAgentsResponse
	(*GetAgentRequest)(nil),    // 2: dart.gateway.agent.v1.GetAgentRequest
	(*CreateAgentRequest)(nil), // 3: dart.gateway.agent.v1.CreateAgentRequest
	(*DeleteAgentRequest)(nil), // 4: dart.gateway.agent.v1.DeleteAgentRequest
	(*Agent)(nil),              // 5: dart.gateway.agent.v1.Agent
	(*emptypb.Empty)(nil),      // 6: google.protobuf.Empty
}
var file_dart_gateway_agent_v1_agent_service_proto_depIdxs = []int32{
	5, // 0: dart.gateway.agent.v1.ListAgentsResponse.agents:type_name -> dart.gateway.agent.v1.Agent
	5, // 1: dart.gateway.agent.v1.CreateAgentRequest.agent:type_name -> dart.gateway.agent.v1.Agent
	0, // 2: dart.gateway.agent.v1.AgentService.ListAgents:input_type -> dart.gateway.agent.v1.ListAgentsRequest
	2, // 3: dart.gateway.agent.v1.AgentService.GetAgent:input_type -> dart.gateway.agent.v1.GetAgentRequest
	3, // 4: dart.gateway.agent.v1.AgentService.CreateAgent:input_type -> dart.gateway.agent.v1.CreateAgentRequest
	4, // 5: dart.gateway.agent.v1.AgentService.DeleteAgent:input_type -> dart.gateway.agent.v1.DeleteAgentRequest
	1, // 6: dart.gateway.agent.v1.AgentService.ListAgents:output_type -> dart.gateway.agent.v1.ListAgentsResponse
	5, // 7: dart.gateway.agent.v1.AgentService.GetAgent:output_type -> dart.gateway.agent.v1.Agent
	5, // 8: dart.gateway.agent.v1.AgentService.CreateAgent:output_type -> dart.gateway.agent.v1.Agent
	6, // 9: dart.gateway.agent.v1.AgentService.DeleteAgent:output_type -> google.protobuf.Empty
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dart_gateway_agent_v1_agent_service_proto_init() }
func file_dart_gateway_agent_v1_agent_service_proto_init() {
	if File_dart_gateway_agent_v1_agent_service_proto != nil {
		return
	}
	file_dart_gateway_agent_v1_agent_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dart_gateway_agent_v1_agent_service_proto_rawDesc), len(file_dart_gateway_agent_v1_agent_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dart_gateway_agent_v1_agent_service_proto_goTypes,
		DependencyIndexes: file_dart_gateway_agent_v1_agent_service_proto_depIdxs,
		MessageInfos:      file_dart_gateway_agent_v1_agent_service_proto_msgTypes,
	}.Build()
	File_dart_gateway_agent_v1_agent_service_proto = out.File
	file_dart_gateway_agent_v1_agent_service_proto_goTypes = nil
	file_dart_gateway_agent_v1_agent_service_proto_depIdxs = nil
}
