// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: dart/gateway/agent/v1/agent.proto

package agent

import (
	v1 "github.com/10Narratives/dart/pkg/dart/domain/capabilities/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Agent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the agent.
	// Format: `projects/{project}/agents/{agent}`
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Compute capabilities of the agent (CPU, GPU).
	ComputeCapabilities *v1.ComputeCapabilities `protobuf:"bytes,2,opt,name=compute_capabilities,json=computeCapabilities,proto3" json:"compute_capabilities,omitempty"`
	// Memory capabilities of the agent.
	MemoryCapabilities *v1.MemoryCapabilities `protobuf:"bytes,3,opt,name=memory_capabilities,json=memoryCapabilities,proto3" json:"memory_capabilities,omitempty"`
	// Network capabilities of the agent.
	NetworkCapabilities *v1.NetworkCapabilities `protobuf:"bytes,4,opt,name=network_capabilities,json=networkCapabilities,proto3" json:"network_capabilities,omitempty"`
	// Task execution capabilities of the agent.
	TaskExecutionCapabilities *v1.TaskExecutionCapabilities `protobuf:"bytes,5,opt,name=task_execution_capabilities,json=taskExecutionCapabilities,proto3" json:"task_execution_capabilities,omitempty"`
	// JSON schema describing the expected parameters format for this agent.
	// The schema must be compliant with JSON Schema Draft 7.
	// Example:
	//
	//	{
	//	  "type": "object",
	//	  "properties": {
	//	    "input_data": {"type": "string"},
	//	    "timeout": {"type": "integer", "default": 30}
	//	  },
	//	  "required": ["input_data"]
	//	}
	ParametersSchema string `protobuf:"bytes,7,opt,name=parameters_schema,json=parametersSchema,proto3" json:"parameters_schema,omitempty"`
	// Human-readable descriptions of the parameters (key: parameter name, value:
	// description).
	ParametersDescriptions map[string]string `protobuf:"bytes,8,rep,name=parameters_descriptions,json=parametersDescriptions,proto3" json:"parameters_descriptions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Example parameters structure in Struct format for documentation purposes.
	ExampleParameters *structpb.Struct `protobuf:"bytes,9,opt,name=example_parameters,json=exampleParameters,proto3" json:"example_parameters,omitempty"`
	// Output only. Creation timestamp.
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_dart_gateway_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_dart_gateway_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_dart_gateway_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *Agent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Agent) GetComputeCapabilities() *v1.ComputeCapabilities {
	if x != nil {
		return x.ComputeCapabilities
	}
	return nil
}

func (x *Agent) GetMemoryCapabilities() *v1.MemoryCapabilities {
	if x != nil {
		return x.MemoryCapabilities
	}
	return nil
}

func (x *Agent) GetNetworkCapabilities() *v1.NetworkCapabilities {
	if x != nil {
		return x.NetworkCapabilities
	}
	return nil
}

func (x *Agent) GetTaskExecutionCapabilities() *v1.TaskExecutionCapabilities {
	if x != nil {
		return x.TaskExecutionCapabilities
	}
	return nil
}

func (x *Agent) GetParametersSchema() string {
	if x != nil {
		return x.ParametersSchema
	}
	return ""
}

func (x *Agent) GetParametersDescriptions() map[string]string {
	if x != nil {
		return x.ParametersDescriptions
	}
	return nil
}

func (x *Agent) GetExampleParameters() *structpb.Struct {
	if x != nil {
		return x.ExampleParameters
	}
	return nil
}

func (x *Agent) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

var File_dart_gateway_agent_v1_agent_proto protoreflect.FileDescriptor

const file_dart_gateway_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"!dart/gateway/agent/v1/agent.proto\x12\x15dart.gateway.agent.v1\x1a6dart/domain/capabilities/v1/compute_capabilities.proto\x1a5dart/domain/capabilities/v1/memory_capabilities.proto\x1a6dart/domain/capabilities/v1/network_capabilities.proto\x1a=dart/domain/capabilities/v1/task_execution_capabilities.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/api/resource.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xaa\a\n" +
	"\x05Agent\x12.\n" +
	"\x04name\x18\x01 \x01(\tB\x1a\xe0A\b\xfaA\x14\n" +
	"\x12dart.gateway/AgentR\x04name\x12c\n" +
	"\x14compute_capabilities\x18\x02 \x01(\v20.dart.domain.capabilities.v1.ComputeCapabilitiesR\x13computeCapabilities\x12`\n" +
	"\x13memory_capabilities\x18\x03 \x01(\v2/.dart.domain.capabilities.v1.MemoryCapabilitiesR\x12memoryCapabilities\x12c\n" +
	"\x14network_capabilities\x18\x04 \x01(\v20.dart.domain.capabilities.v1.NetworkCapabilitiesR\x13networkCapabilities\x12v\n" +
	"\x1btask_execution_capabilities\x18\x05 \x01(\v26.dart.domain.capabilities.v1.TaskExecutionCapabilitiesR\x19taskExecutionCapabilities\x120\n" +
	"\x11parameters_schema\x18\a \x01(\tB\x03\xe0A\x01R\x10parametersSchema\x12v\n" +
	"\x17parameters_descriptions\x18\b \x03(\v28.dart.gateway.agent.v1.Agent.ParametersDescriptionsEntryB\x03\xe0A\x01R\x16parametersDescriptions\x12K\n" +
	"\x12example_parameters\x18\t \x01(\v2\x17.google.protobuf.StructB\x03\xe0A\x01R\x11exampleParameters\x12@\n" +
	"\vcreate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\x1aI\n" +
	"\x1bParametersDescriptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:I\xeaAF\n" +
	"\x12dart.gateway/Agent\x12!projects/{project}/agents/{agent}*\x06agents2\x05agentB>Z<github.com/10Narratives/dart/pkg/dart/gateway/agent/v1;agentb\x06proto3"

var (
	file_dart_gateway_agent_v1_agent_proto_rawDescOnce sync.Once
	file_dart_gateway_agent_v1_agent_proto_rawDescData []byte
)

func file_dart_gateway_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_dart_gateway_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_dart_gateway_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dart_gateway_agent_v1_agent_proto_rawDesc), len(file_dart_gateway_agent_v1_agent_proto_rawDesc)))
	})
	return file_dart_gateway_agent_v1_agent_proto_rawDescData
}

var file_dart_gateway_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dart_gateway_agent_v1_agent_proto_goTypes = []any{
	(*Agent)(nil),                        // 0: dart.gateway.agent.v1.Agent
	nil,                                  // 1: dart.gateway.agent.v1.Agent.ParametersDescriptionsEntry
	(*v1.ComputeCapabilities)(nil),       // 2: dart.domain.capabilities.v1.ComputeCapabilities
	(*v1.MemoryCapabilities)(nil),        // 3: dart.domain.capabilities.v1.MemoryCapabilities
	(*v1.NetworkCapabilities)(nil),       // 4: dart.domain.capabilities.v1.NetworkCapabilities
	(*v1.TaskExecutionCapabilities)(nil), // 5: dart.domain.capabilities.v1.TaskExecutionCapabilities
	(*structpb.Struct)(nil),              // 6: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),        // 7: google.protobuf.Timestamp
}
var file_dart_gateway_agent_v1_agent_proto_depIdxs = []int32{
	2, // 0: dart.gateway.agent.v1.Agent.compute_capabilities:type_name -> dart.domain.capabilities.v1.ComputeCapabilities
	3, // 1: dart.gateway.agent.v1.Agent.memory_capabilities:type_name -> dart.domain.capabilities.v1.MemoryCapabilities
	4, // 2: dart.gateway.agent.v1.Agent.network_capabilities:type_name -> dart.domain.capabilities.v1.NetworkCapabilities
	5, // 3: dart.gateway.agent.v1.Agent.task_execution_capabilities:type_name -> dart.domain.capabilities.v1.TaskExecutionCapabilities
	1, // 4: dart.gateway.agent.v1.Agent.parameters_descriptions:type_name -> dart.gateway.agent.v1.Agent.ParametersDescriptionsEntry
	6, // 5: dart.gateway.agent.v1.Agent.example_parameters:type_name -> google.protobuf.Struct
	7, // 6: dart.gateway.agent.v1.Agent.create_time:type_name -> google.protobuf.Timestamp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_dart_gateway_agent_v1_agent_proto_init() }
func file_dart_gateway_agent_v1_agent_proto_init() {
	if File_dart_gateway_agent_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dart_gateway_agent_v1_agent_proto_rawDesc), len(file_dart_gateway_agent_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dart_gateway_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_dart_gateway_agent_v1_agent_proto_depIdxs,
		MessageInfos:      file_dart_gateway_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_dart_gateway_agent_v1_agent_proto = out.File
	file_dart_gateway_agent_v1_agent_proto_goTypes = nil
	file_dart_gateway_agent_v1_agent_proto_depIdxs = nil
}
