// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: dart/gateway/task/v1/task_service.proto

package task

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListTasksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The agent to list tasks from.
	// Format: `projects/{project}/agents/{agent}`
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The maximum number of tasks to return.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// A page token, received from a previous `ListTasks` call.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_dart_gateway_task_v1_task_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dart_gateway_task_v1_task_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_dart_gateway_task_v1_task_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListTasksRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListTasksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTasksRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListTasksResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of tasks.
	Tasks []*Task `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	// A token to retrieve the next page of results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_dart_gateway_task_v1_task_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dart_gateway_task_v1_task_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_dart_gateway_task_v1_task_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListTasksResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The resource name of the task to retrieve.
	// Format: `projects/{project}/agents/{agent}/tasks/{task}`
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_dart_gateway_task_v1_task_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dart_gateway_task_v1_task_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_dart_gateway_task_v1_task_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The agent to create a task in.
	// Format: `projects/{project}/agents/{agent}`
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Optional. The task ID to use. If not provided, the system will generate
	// one.
	TaskId string `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// Required. The task to create.
	Task          *Task `protobuf:"bytes,3,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_dart_gateway_task_v1_task_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dart_gateway_task_v1_task_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_dart_gateway_task_v1_task_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTaskRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CreateTaskRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type CancelTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The resource name of the task to cancel.
	// Format: `projects/{project}/agents/{agent}/tasks/{task}`
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_dart_gateway_task_v1_task_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dart_gateway_task_v1_task_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_dart_gateway_task_v1_task_service_proto_rawDescGZIP(), []int{4}
}

func (x *CancelTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_dart_gateway_task_v1_task_service_proto protoreflect.FileDescriptor

const file_dart_gateway_task_v1_task_service_proto_rawDesc = "" +
	"\n" +
	"'dart/gateway/task/v1/task_service.proto\x12\x14dart.gateway.task.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a google/protobuf/field_mask.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fdart/gateway/task/v1/task.proto\"\x8c\x01\n" +
	"\x10ListTasksRequest\x122\n" +
	"\x06parent\x18\x01 \x01(\tB\x1a\xe0A\x02\xfaA\x14\n" +
	"\x12dart.gateway/AgentR\x06parent\x12 \n" +
	"\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01R\bpageSize\x12\"\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tB\x03\xe0A\x01R\tpageToken\"m\n" +
	"\x11ListTasksResponse\x120\n" +
	"\x05tasks\x18\x01 \x03(\v2\x1a.dart.gateway.task.v1.TaskR\x05tasks\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"?\n" +
	"\x0eGetTaskRequest\x12-\n" +
	"\x04name\x18\x01 \x01(\tB\x19\xe0A\x02\xfaA\x13\n" +
	"\x11dart.gateway/TaskR\x04name\"\x9a\x01\n" +
	"\x11CreateTaskRequest\x122\n" +
	"\x06parent\x18\x01 \x01(\tB\x1a\xe0A\x02\xfaA\x14\n" +
	"\x12dart.gateway/AgentR\x06parent\x12\x1c\n" +
	"\atask_id\x18\x02 \x01(\tB\x03\xe0A\x01R\x06taskId\x123\n" +
	"\x04task\x18\x03 \x01(\v2\x1a.dart.gateway.task.v1.TaskB\x03\xe0A\x02R\x04task\"B\n" +
	"\x11CancelTaskRequest\x12-\n" +
	"\x04name\x18\x01 \x01(\tB\x19\xe0A\x02\xfaA\x13\n" +
	"\x11dart.gateway/TaskR\x04name2\xca\x04\n" +
	"\vTaskService\x12\x92\x01\n" +
	"\tListTasks\x12&.dart.gateway.task.v1.ListTasksRequest\x1a'.dart.gateway.task.v1.ListTasksResponse\"4\x82\xd3\xe4\x93\x02.\x12,/v1alpha1/{parent=projects/*/agents/*}/tasks\x12\x81\x01\n" +
	"\aGetTask\x12$.dart.gateway.task.v1.GetTaskRequest\x1a\x1a.dart.gateway.task.v1.Task\"4\x82\xd3\xe4\x93\x02.\x12,/v1alpha1/{name=projects/*/agents/*/tasks/*}\x12\x8d\x01\n" +
	"\n" +
	"CreateTask\x12'.dart.gateway.task.v1.CreateTaskRequest\x1a\x1a.dart.gateway.task.v1.Task\":\x82\xd3\xe4\x93\x024:\x04task\",/v1alpha1/{parent=projects/*/agents/*}/tasks\x12\x91\x01\n" +
	"\n" +
	"CancelTask\x12'.dart.gateway.task.v1.CancelTaskRequest\x1a\x1a.dart.gateway.task.v1.Task\">\x82\xd3\xe4\x93\x028:\x01*\"3/v1alpha1/{name=projects/*/agents/*/tasks/*}:cancelB<Z:github.com/10Narratives/dart/pkg/dart/gateway/task/v1;taskb\x06proto3"

var (
	file_dart_gateway_task_v1_task_service_proto_rawDescOnce sync.Once
	file_dart_gateway_task_v1_task_service_proto_rawDescData []byte
)

func file_dart_gateway_task_v1_task_service_proto_rawDescGZIP() []byte {
	file_dart_gateway_task_v1_task_service_proto_rawDescOnce.Do(func() {
		file_dart_gateway_task_v1_task_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dart_gateway_task_v1_task_service_proto_rawDesc), len(file_dart_gateway_task_v1_task_service_proto_rawDesc)))
	})
	return file_dart_gateway_task_v1_task_service_proto_rawDescData
}

var file_dart_gateway_task_v1_task_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_dart_gateway_task_v1_task_service_proto_goTypes = []any{
	(*ListTasksRequest)(nil),  // 0: dart.gateway.task.v1.ListTasksRequest
	(*ListTasksResponse)(nil), // 1: dart.gateway.task.v1.ListTasksResponse
	(*GetTaskRequest)(nil),    // 2: dart.gateway.task.v1.GetTaskRequest
	(*CreateTaskRequest)(nil), // 3: dart.gateway.task.v1.CreateTaskRequest
	(*CancelTaskRequest)(nil), // 4: dart.gateway.task.v1.CancelTaskRequest
	(*Task)(nil),              // 5: dart.gateway.task.v1.Task
}
var file_dart_gateway_task_v1_task_service_proto_depIdxs = []int32{
	5, // 0: dart.gateway.task.v1.ListTasksResponse.tasks:type_name -> dart.gateway.task.v1.Task
	5, // 1: dart.gateway.task.v1.CreateTaskRequest.task:type_name -> dart.gateway.task.v1.Task
	0, // 2: dart.gateway.task.v1.TaskService.ListTasks:input_type -> dart.gateway.task.v1.ListTasksRequest
	2, // 3: dart.gateway.task.v1.TaskService.GetTask:input_type -> dart.gateway.task.v1.GetTaskRequest
	3, // 4: dart.gateway.task.v1.TaskService.CreateTask:input_type -> dart.gateway.task.v1.CreateTaskRequest
	4, // 5: dart.gateway.task.v1.TaskService.CancelTask:input_type -> dart.gateway.task.v1.CancelTaskRequest
	1, // 6: dart.gateway.task.v1.TaskService.ListTasks:output_type -> dart.gateway.task.v1.ListTasksResponse
	5, // 7: dart.gateway.task.v1.TaskService.GetTask:output_type -> dart.gateway.task.v1.Task
	5, // 8: dart.gateway.task.v1.TaskService.CreateTask:output_type -> dart.gateway.task.v1.Task
	5, // 9: dart.gateway.task.v1.TaskService.CancelTask:output_type -> dart.gateway.task.v1.Task
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dart_gateway_task_v1_task_service_proto_init() }
func file_dart_gateway_task_v1_task_service_proto_init() {
	if File_dart_gateway_task_v1_task_service_proto != nil {
		return
	}
	file_dart_gateway_task_v1_task_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dart_gateway_task_v1_task_service_proto_rawDesc), len(file_dart_gateway_task_v1_task_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dart_gateway_task_v1_task_service_proto_goTypes,
		DependencyIndexes: file_dart_gateway_task_v1_task_service_proto_depIdxs,
		MessageInfos:      file_dart_gateway_task_v1_task_service_proto_msgTypes,
	}.Build()
	File_dart_gateway_task_v1_task_service_proto = out.File
	file_dart_gateway_task_v1_task_service_proto_goTypes = nil
	file_dart_gateway_task_v1_task_service_proto_depIdxs = nil
}
