// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: dart/gateway/task/v1/task.proto

package task

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Current state of the task.
type Task_State int32

const (
	Task_STATE_UNSPECIFIED Task_State = 0
	Task_STATE_PENDING     Task_State = 1 // Task is queued but not yet started
	Task_STATE_RUNNING     Task_State = 2 // Task is currently executing
	Task_STATE_FAILED      Task_State = 3 // Task execution failed
	Task_STATE_EXPIRED     Task_State = 4 // Task exceeded its TTL before execution
	Task_STATE_COMPLETED   Task_State = 5 // Task completed successfully
	Task_STATE_CANCELED    Task_State = 6 // Task was explicitly canceled
)

// Enum value maps for Task_State.
var (
	Task_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_PENDING",
		2: "STATE_RUNNING",
		3: "STATE_FAILED",
		4: "STATE_EXPIRED",
		5: "STATE_COMPLETED",
		6: "STATE_CANCELED",
	}
	Task_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_PENDING":     1,
		"STATE_RUNNING":     2,
		"STATE_FAILED":      3,
		"STATE_EXPIRED":     4,
		"STATE_COMPLETED":   5,
		"STATE_CANCELED":    6,
	}
)

func (x Task_State) Enum() *Task_State {
	p := new(Task_State)
	*p = x
	return p
}

func (x Task_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Task_State) Descriptor() protoreflect.EnumDescriptor {
	return file_dart_gateway_task_v1_task_proto_enumTypes[0].Descriptor()
}

func (Task_State) Type() protoreflect.EnumType {
	return &file_dart_gateway_task_v1_task_proto_enumTypes[0]
}

func (x Task_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Task_State.Descriptor instead.
func (Task_State) EnumDescriptor() ([]byte, []int) {
	return file_dart_gateway_task_v1_task_proto_rawDescGZIP(), []int{0, 0}
}

type Task struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the task.
	// Format: `projects/{project}/agents/{agent}/tasks/{task}`
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The resource name of the assigned resource.
	// Format: `projects/{project}/resources/{resource}`
	AssignedResource string `protobuf:"bytes,2,opt,name=assigned_resource,json=assignedResource,proto3" json:"assigned_resource,omitempty"`
	// Time-to-live for the task. If the task is not started before this duration
	// elapses, it will be automatically expired and marked as failed.
	Ttl *durationpb.Duration `protobuf:"bytes,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	// Output only. Creation timestamp.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// Output only. Start timestamp when the task begins execution.
	StartTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Output only. Completion timestamp when the task finishes execution.
	EndTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	State   Task_State             `protobuf:"varint,7,opt,name=state,proto3,enum=dart.gateway.task.v1.Task_State" json:"state,omitempty"`
	// Task-specific parameters (JSON-encoded).
	Parameters    string `protobuf:"bytes,8,opt,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_dart_gateway_task_v1_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_dart_gateway_task_v1_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_dart_gateway_task_v1_task_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetAssignedResource() string {
	if x != nil {
		return x.AssignedResource
	}
	return ""
}

func (x *Task) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

func (x *Task) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Task) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Task) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *Task) GetState() Task_State {
	if x != nil {
		return x.State
	}
	return Task_STATE_UNSPECIFIED
}

func (x *Task) GetParameters() string {
	if x != nil {
		return x.Parameters
	}
	return ""
}

var File_dart_gateway_task_v1_task_proto protoreflect.FileDescriptor

const file_dart_gateway_task_v1_task_proto_rawDesc = "" +
	"\n" +
	"\x1fdart/gateway/task/v1/task.proto\x12\x14dart.gateway.task.v1\x1a\x19google/api/resource.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xbd\x05\n" +
	"\x04Task\x12-\n" +
	"\x04name\x18\x01 \x01(\tB\x19\xe0A\b\xfaA\x13\n" +
	"\x11dart.gateway/TaskR\x04name\x12J\n" +
	"\x11assigned_resource\x18\x02 \x01(\tB\x1d\xe0A\x01\xfaA\x17\n" +
	"\x15dart.gateway/ResourceR\x10assignedResource\x120\n" +
	"\x03ttl\x18\x03 \x01(\v2\x19.google.protobuf.DurationB\x03\xe0A\x01R\x03ttl\x12@\n" +
	"\vcreate_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\x12>\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\tstartTime\x12:\n" +
	"\bend_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\aendTime\x12;\n" +
	"\x05state\x18\a \x01(\x0e2 .dart.gateway.task.v1.Task.StateB\x03\xe0A\x03R\x05state\x12#\n" +
	"\n" +
	"parameters\x18\b \x01(\tB\x03\xe0A\x02R\n" +
	"parameters\"\x92\x01\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATE_PENDING\x10\x01\x12\x11\n" +
	"\rSTATE_RUNNING\x10\x02\x12\x10\n" +
	"\fSTATE_FAILED\x10\x03\x12\x11\n" +
	"\rSTATE_EXPIRED\x10\x04\x12\x13\n" +
	"\x0fSTATE_COMPLETED\x10\x05\x12\x12\n" +
	"\x0eSTATE_CANCELED\x10\x06:S\xeaAP\n" +
	"\x11dart.gateway/Task\x12.projects/{project}/agents/{agent}/tasks/{task}*\x05tasks2\x04taskB<Z:github.com/10Narratives/dart/pkg/dart/gateway/task/v1;taskb\x06proto3"

var (
	file_dart_gateway_task_v1_task_proto_rawDescOnce sync.Once
	file_dart_gateway_task_v1_task_proto_rawDescData []byte
)

func file_dart_gateway_task_v1_task_proto_rawDescGZIP() []byte {
	file_dart_gateway_task_v1_task_proto_rawDescOnce.Do(func() {
		file_dart_gateway_task_v1_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dart_gateway_task_v1_task_proto_rawDesc), len(file_dart_gateway_task_v1_task_proto_rawDesc)))
	})
	return file_dart_gateway_task_v1_task_proto_rawDescData
}

var file_dart_gateway_task_v1_task_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dart_gateway_task_v1_task_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dart_gateway_task_v1_task_proto_goTypes = []any{
	(Task_State)(0),               // 0: dart.gateway.task.v1.Task.State
	(*Task)(nil),                  // 1: dart.gateway.task.v1.Task
	(*durationpb.Duration)(nil),   // 2: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_dart_gateway_task_v1_task_proto_depIdxs = []int32{
	2, // 0: dart.gateway.task.v1.Task.ttl:type_name -> google.protobuf.Duration
	3, // 1: dart.gateway.task.v1.Task.create_time:type_name -> google.protobuf.Timestamp
	3, // 2: dart.gateway.task.v1.Task.start_time:type_name -> google.protobuf.Timestamp
	3, // 3: dart.gateway.task.v1.Task.end_time:type_name -> google.protobuf.Timestamp
	0, // 4: dart.gateway.task.v1.Task.state:type_name -> dart.gateway.task.v1.Task.State
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_dart_gateway_task_v1_task_proto_init() }
func file_dart_gateway_task_v1_task_proto_init() {
	if File_dart_gateway_task_v1_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dart_gateway_task_v1_task_proto_rawDesc), len(file_dart_gateway_task_v1_task_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dart_gateway_task_v1_task_proto_goTypes,
		DependencyIndexes: file_dart_gateway_task_v1_task_proto_depIdxs,
		EnumInfos:         file_dart_gateway_task_v1_task_proto_enumTypes,
		MessageInfos:      file_dart_gateway_task_v1_task_proto_msgTypes,
	}.Build()
	File_dart_gateway_task_v1_task_proto = out.File
	file_dart_gateway_task_v1_task_proto_goTypes = nil
	file_dart_gateway_task_v1_task_proto_depIdxs = nil
}
